# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  displayName: "install node & NPM"
  inputs:
    version: 10.14.2
    
- task: Npm@1
  displayName: 'Install Dependencies'
  inputs:
    command: custom
    verbose: false
    customCommand: --production install

- task: Npm@1
  displayName: 'Run Build'
  inputs:
    command: custom
    verbose: false
    customCommand: run compile



